### ISSUE TITLE
Actions page is not displaying any action

### ISSUE THREAD

**Issue by duranmla** [debtcollective/campaign-api#17]
**What:**
The actions page is currently empty.

**Why:**
There is no code that attach a certain action to our currentCampaign

**Expected:**
- [x] User enters to `actions/` to see a list of actions links
- [x] User can see completed actions with a visual feedback on every action link at `actions/`
- [x] User click the action link and get redirected to the `actions/:action_slug`

**Comment by duranmla** [comment]
Keep in mind that the current implemented flow takes the user to `/data-dues` what happen with actions? Is `data-dues` a type of actions?

If we create a `UserAction` with the user (currentUser) a campaign (currentCampaign) and the action as data-due id we should be able to see data dues within the actions page.

**Comment by orlando** [comment]
@duranmla because after the user joined a campaign it wasn't showing the actions list, I redirect them to data-dues. This is the flow we have discussed:

1. User joins a campaign
2. User is redirected to the actions page
3. User is able to complete any of the actions of the page
4. Once an action is completed, the actions list would display feedback about it.

**Comment by duranmla** [comment]
According to a new decision made after a conversation yesterday. What we will want now is to: `/actions` to render the list of available actions such as _"data-dues"_ when user click it will be redirected to the `/actions/:action_slug` which upon complete the user can see a feedback on the list rendered at `/actions`

**Comment by orlando** [comment]
This should be fixed with #24
